[package]
name = "ammocount"
version = "0.1.0"
edition = "2018"

[dependencies]
tf-demo-parser = { version = "0.4", git = "https://github.com/demostf/parser" }
fnv = "1"
main_error = "0.1"
once_cell = "1"

[profile.dev]
opt-level = 2